apiVersion: v1
kind: ConfigMap
metadata:
  name: gym-config
  namespace: gym  # Change this to your desired namespace
data:
  # Application Configuration
  BETTER_AUTH_URL: "http://gym-app-service.gym.svc.cluster.local:3000"
  NEXT_PUBLIC_APP_URL: "http://gym-app-service.gym.svc.cluster.local:3000"
  SEED_SAMPLE_DATA: "false"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: gym
data:
  init-workout-cool.sql: |
    -- Create the workout-cool database if it doesn't exist
    SELECT 'CREATE DATABASE "workout-cool"'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'workout-cool')\gexec
    
    -- Connect to the workout-cool database and set up privileges
    \c "workout-cool"
    
    -- Grant all privileges to the gym user
    GRANT ALL PRIVILEGES ON DATABASE "workout-cool" TO gym;
    GRANT ALL PRIVILEGES ON SCHEMA public TO gym;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO gym;
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO gym;
    
    -- Set default privileges for future objects
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO gym;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO gym;
