apiVersion: v1
kind: PersistentVolume
metadata:
  name: gym-postgres-pv
  namespace: gym
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/gym/data/postgres